language: ruby
script: "rspec"
rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
notifications:
  irc:
    channels:
      - "chat.freenode.net#chorn"
    on_success: change
    on_failure: always
